version: "3.8"

services:
  mongo:
    image: mongo:latest
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: linhx
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: sso
    ports:
      - 27017:27017
  sso:
    build: ./
    depends_on:
      - mongo
    ports:
      - 3000:3000
      - 5005:5005
    volumes:
      - .:/app
    working_dir: /app
    command: ./spring-sso/gradlew -p ./spring-sso --project-cache-dir /tmp/gradle-cache bootRun -DDEBUG=true
    environment:
      APP_PORT: 3000
      CORS_ORIGINS: http://localhost:8080,http://linhx.local
      SECURITY_DOMAIN: linhx.local
      SSO_DOMAIN: sso.linhx.local
      ACCESS_TOKEN_SECRET: access_token_keys_used_with_HMAC-SHA_algorithms_must_have_a_size_greater_than_or_equal_256_bits
      REFRESH_TOKEN_SECRET: refresh_token_keys_used_with_HMAC-SHA_algorithms_must_have_a_size_greater_than_or_equal_256_bits
      LLHS_SECRET: llhs_keys_used_with_HMAC-SHA_algorithms_must_have_a_size_greater_than_or_equal_256_bits
      REQUEST_ACCESS_TOKEN_SECRET: request_access_token_keys_used_with_HMAC-SHA_algorithms_must_have_a_size_greater_than_or_equal_256_bits
      DATABASE_HOST: mongo
      DATABASE_USER: linhx
      DATABASE_PASSWORD: root
      DATABASE_NAME: sso
      DATABASE_PORT: 27017
      SENDGRID_KEY: sendgrid_api_key