server:
  port: 3000

security:
  cors:
    origins: http://localhost:8080
    methods: '*'
  jwt:
    tokenSecret: keys_used_with_HMAC-SHA_algorithms_must_have_a_size_greater_than_or_equal_256_bits
    refreshTokenSecret: keys_used_with_HMAC-SHA_algorithms_must_have_a_size_greater_than_or_equal_256_bits
